"""Cross-references every raw capture batch (data/raw/<game>/<batch>/images/) against the
current labeled pool + duplicate archive, by timestamp embedded in the filename, to report
which batches have already been merged into training and which are still available to use.
Writes a table to data/raw/BATCH_STATUS.md (data/ is gitignored — local reference only).
"""

import re
from pathlib import Path

RAW_DIR = Path("data/raw")
POOL_DIR = Path("data/labeled/v39-pool-dedupe-fix-1659")
ARCHIVE_DIR = Path("data/labeled/_duplicates_archive")
OUT_PATH = RAW_DIR / "BATCH_STATUS.md"

# Every naming variant seen (raw captures, curated batches with a microsecond suffix, Roboflow
# re-exports with a "_png.rf.<id>" suffix) embeds this same "YYYYMMDD_HHMMSS" — match on that
# instead of pixel hashing, since it's fast, exact, and sessions never overlap in wall-clock time.
TIMESTAMP_RE = re.compile(r"(\d{8}_\d{6})")


def timestamp_keys(images_dir: Path) -> set[str]:
    keys = set()
    for p in images_dir.glob("*.png"):
        match = TIMESTAMP_RE.search(p.stem)
        if match:
            keys.add(match.group(1))
    return keys


def find_batches(raw_dir: Path) -> list[Path]:
    """A 'batch' is any directory that directly contains an images/ subfolder."""
    return sorted(p.parent for p in raw_dir.glob("**/images") if p.is_dir())


def write_used_list(batch_dir: Path, reference_keys: set[str]) -> int:
    """For a partially-merged batch, list which of its images (by filename) are already used —
    so a future selection pass knows what's left to pick from in that same batch."""
    used = sorted(
        p.name
        for p in (batch_dir / "images").glob("*.png")
        if (m := TIMESTAMP_RE.search(p.stem)) and m.group(1) in reference_keys
    )
    (batch_dir / "used_screenshots.txt").write_text("\n".join(used) + "\n")
    return len(used)


def classify(matched: int, total: int) -> str:
    if total == 0:
        return "n/a"
    pct = matched / total
    if pct >= 0.95:
        return "merged"
    if pct > 0:
        return "partially merged"
    return "available"


def main() -> None:
    reference_keys: set[str] = set()
    for split_dir in (
        POOL_DIR / "train" / "images",
        POOL_DIR / "valid" / "images",
        ARCHIVE_DIR / "images",
    ):
        reference_keys |= timestamp_keys(split_dir)

    batches = find_batches(RAW_DIR)

    lines = [
        "# Raw batch status",
        "",
        f"Auto-generated by `helpers/raw_batch_status.py`. Reference pool: `{POOL_DIR.name}` + `{ARCHIVE_DIR.name}`.",
        "A batch counts as **merged** if >=95% of its images (by embedded timestamp) are present in the "
        "reference set, **partially merged** if some are, **available** if none are — i.e. still usable for a future batch. "
        "Every **partially merged** batch gets a `used_screenshots.txt` written into its own folder, listing exactly "
        "which of its images are already taken — anything in `images/` not listed there is still free to use.",
        "",
        "| game | batch | images | has labels/ | matched in labeled | status |",
        "|---|---|---|---|---|---|",
    ]

    for batch_dir in batches:
        keys = timestamp_keys(batch_dir / "images")
        matched = len(keys & reference_keys)
        total = len(keys)
        has_labels = "yes" if (batch_dir / "labels").exists() else "no"
        status = classify(matched, total)
        if status == "partially merged":
            write_used_list(batch_dir, reference_keys)
        game = batch_dir.parent.name if batch_dir.parent != RAW_DIR else batch_dir.name
        batch_name = batch_dir.name if batch_dir.parent != RAW_DIR else "-"
        lines.append(
            f"| {game} | {batch_name} | {total} | {has_labels} | {matched} ({matched / total:.0%}) | {status} |"
        )

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}")

    n_merged = sum(1 for line in lines if line.endswith("| merged |"))
    n_partial = sum(1 for line in lines if line.endswith("| partially merged |"))
    n_available = sum(1 for line in lines if line.endswith("| available |"))
    print(f"merged={n_merged} partially_merged={n_partial} available={n_available}")


if __name__ == "__main__":
    main()
