"""Cross-references every raw capture batch against the current labeled pool + duplicate
archive, by timestamp embedded in the filename, to report which batches have already been
merged into training and which are still available to use. Writes a table to
data/raw/BATCH_STATUS.md (data/ is gitignored — local reference only).
"""

import re
from pathlib import Path

RAW_DIR = Path("data/raw")
POOL_DIR = Path("data/labeled/v39-pool-dedupe-fix-1659")
ARCHIVE_DIR = Path("data/labeled/_duplicates_archive")
OUT_PATH = RAW_DIR / "BATCH_STATUS.md"

# Every naming variant seen (raw captures, curated batches with a microsecond suffix, Roboflow
# re-exports with a "_png.rf.<id>" suffix) embeds a "YYYYMMDD_HHMMSS" — optionally followed by a
# microsecond suffix on batches captured faster than 1/s (game_4/game_5, dead_player_curated_*).
# Match on the longest available precision: two screenshots in the same batch can share a second
# (confirmed on dead_player_curated), so dropping the microsecond suffix would make them
# indistinguishable and let one merged image mark both as "used".
TIMESTAMP_RE = re.compile(r"(\d{8}_\d{6}(?:_\d+)?)")


def file_keys(images_dir: Path) -> dict[str, str]:
    """Maps each image filename to its extracted timestamp key."""
    keys = {}
    for p in images_dir.glob("*.png"):
        match = TIMESTAMP_RE.search(p.stem)
        if match:
            keys[p.name] = match.group(1)
    return keys


def find_batches(raw_dir: Path) -> list[tuple[str, str, Path]]:
    """Returns (game, batch_label, images_dir) triples. A 'batch' is either a directory with an
    images/ subfolder, or a directory containing loose *.png files directly — both patterns exist
    in this project's raw captures (leftover screenshots directly under game_2/, game_3/, and
    capture_screenshots.py's current flat single-session output)."""
    batches = []
    for images_dir in sorted(raw_dir.glob("**/images")):
        if images_dir.is_dir():
            batch_dir = images_dir.parent
            if batch_dir.parent == raw_dir:
                batches.append((batch_dir.name, "-", images_dir))
            else:
                batches.append((batch_dir.parent.name, batch_dir.name, images_dir))

    candidates = [raw_dir, *(d for d in raw_dir.iterdir() if d.is_dir())]
    for d in sorted(set(candidates), key=lambda p: p.name):
        if any(d.glob("*.png")):
            game = d.name if d != raw_dir else "-"
            batches.append((game, "(loose)", d))

    return batches


def batch_root(images_dir: Path) -> Path:
    """The batch's own directory — one level up for an images/ subfolder, itself for a loose-file batch."""
    return images_dir.parent if images_dir.name == "images" else images_dir


def write_used_list(
    images_dir: Path, keys_by_file: dict[str, str], reference_keys: set[str]
) -> int:
    """For a partially-merged batch, list which of its images (by filename) are already used —
    so a future selection pass knows what's left to pick from in that same batch."""
    used = sorted(name for name, key in keys_by_file.items() if key in reference_keys)
    (batch_root(images_dir) / "used_screenshots.txt").write_text("\n".join(used) + "\n")
    return len(used)


def classify(matched: int, total: int) -> str:
    if total == 0:
        return "n/a"
    pct = matched / total
    if pct >= 0.95:
        return "merged"
    if pct > 0:
        return "partially merged"
    return "available"


def main() -> None:
    reference_keys: set[str] = set()
    for split_dir in (
        POOL_DIR / "train" / "images",
        POOL_DIR / "valid" / "images",
        ARCHIVE_DIR / "images",
    ):
        reference_keys |= set(file_keys(split_dir).values())

    batches = find_batches(RAW_DIR)

    lines = [
        "# Raw batch status",
        "",
        f"Auto-generated by `helpers/raw_batch_status.py`. Reference pool: `{POOL_DIR.name}` + `{ARCHIVE_DIR.name}`.",
        "A batch counts as **merged** if >=95% of its images (by embedded timestamp) are present in the "
        "reference set, **partially merged** if some are, **available** if none are — i.e. still usable for a future batch. "
        "Every **partially merged** batch gets a `used_screenshots.txt` written into its own folder, listing exactly "
        "which of its images are already taken — anything in `images/` not listed there is still free to use.",
        "",
        "| game | batch | images | has labels/ | matched in labeled | status |",
        "|---|---|---|---|---|---|",
    ]

    for game, batch_name, images_dir in batches:
        keys_by_file = file_keys(images_dir)
        total = len(keys_by_file)
        matched = sum(1 for k in keys_by_file.values() if k in reference_keys)
        has_labels = "yes" if (batch_root(images_dir) / "labels").exists() else "no"
        status = classify(matched, total)
        if status == "partially merged":
            write_used_list(images_dir, keys_by_file, reference_keys)
        pct_str = f"{matched / total:.0%}" if total else "n/a"
        lines.append(
            f"| {game} | {batch_name} | {total} | {has_labels} | {matched} ({pct_str}) | {status} |"
        )

    OUT_PATH.write_text("\n".join(lines) + "\n")
    print(f"Wrote {OUT_PATH}")

    n_merged = sum(1 for line in lines if line.endswith("| merged |"))
    n_partial = sum(1 for line in lines if line.endswith("| partially merged |"))
    n_available = sum(1 for line in lines if line.endswith("| available |"))
    print(f"merged={n_merged} partially_merged={n_partial} available={n_available}")


if __name__ == "__main__":
    main()
